# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df33f98dd2037db8b37b9e1e879ffca8a7549e69068979659cb49752492d930fa622990d4af647ef28ce1d89025fd31bef5effede9ef9c68c8ecee268705680b

test:
  secret_key_base: 941916acab7746f799408370c461ac1f3c622b8d5b32d7bf69d0274668f4d24f6c0fdbbc871f8849aea3410352f4c2b53fbb27f428eca5af68fd0282f643112f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
